### ISSUE TITLE
Error while editing messages

### ISSUE THREAD

**Issue by lewisevan** [JettBurns14/Contest-judging-tool#13]
The edit message button now opens the edit form, but clicking "Save" throws an error: "There was a problem editing this message".

Creating new messages does the same thing.

**Comment by lewisevan** [comment]
Looks like this is actually a DB issue. I've added the required "public" column in the "messages" table and that fixed the issue.

**Comment by JettBurns14** [comment]
Yeah I had a feeling that was the cause. Thanks!
