### ISSUE TITLE
Stop using public KA API for user authorization

### ISSUE THREAD

**Issue by JettBurns14** [JettBurns14/Contest-judging-tool#16]
KA is [removing their public API](https://github.com/Khan/khan-api/commit/f35d8aee5cb4c1fdfc19c3b024b69868cae2286d), including the "/api/v1/user" endpoint, which I use to get a user's KA data during the login/signup process. Obviously my process will break once KA removes the endpoint, so I need to look into an alternative way of getting user data, perhaps with their internal API.

I'm using KA OAuth for the auth process because it's the best way to *know* a user is who they say they are on KA, because they must be logged into their KA account. Any alternative method, if it comes to that, will require this level of certainty.

- https://github.com/Khan/khan-api/wiki/Khan-Academy-API
- https://github.com/Khan/khan-api/wiki/Khan-Academy-API-Authentication

**Comment by lewisevan** [comment]
All of the /v1 API calls were replaced with the /internal calls, so this issue is resolved for now.
