### ISSUE TITLE
Button to "skip" broken entries while judging

### ISSUE THREAD

**Issue by JettBurns14** [JettBurns14/Contest-judging-tool#20]
Sometimes an entry was hidden or deleted after we added its ID to the database, and therefore can't display in the judging page iframe, halting further judging until it's removed from the DB.

Add a skip button to `/judging` that lets the judge move on to a new entry.

**Comment by lewisevan** [comment]
I'm thinking we could make a "skip" button that just submits an evaluation with all 0s for the judging criteria. That would mark the entry as evaluated by the user, and they could then move on to the next one.

I generally check the Results page for entries with an average score of 0 throughout the judging process, and then delete any that are emptied/deleted on KA.

**Comment by JettBurns14** [comment]
Yeah, that would be pretty simple and easy. I can work on this soon.

**Comment by lewisevan** [comment]
This feature was added by Pull Request #39
