### ISSUE TITLE
Editing announcements does not hide tasks modal

### ISSUE THREAD

**Issue by lewisevan** [JettBurns14/Contest-judging-tool#22]
**Describe the bug**
Editing an existing announcement or creating a new announcement does not hide the tasks modal on the home page.

**To Reproduce**
1. Go to the home page.
2. Click "New Announcement"

**Expected behavior**
When the form for editing an announcement appears, all other sections on the page should be hidden.

**Screenshots**
![image](https://user-images.githubusercontent.com/36089251/69112690-82670700-0a46-11ea-9885-47f713cce27e.png)

**Desktop (if applicable, please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by JettBurns14** [comment]
Noticed that too.

The tasks container with ID `"view-tasks-container"` could be grabbed inside `showEditMessageForm()` and `showEditMessageForm()` [here](https://github.com/JettBurns14/Contest-judging-tool/blob/master/public/js/home.js#L82), then hidden like the other containers.

Want to fix this when you have time?

**Comment by lewisevan** [comment]
That's what I was thinking too. I'll look into it tonight.
