### ISSUE TITLE
Replace admin tabs with separate views

### ISSUE THREAD

**Issue by JettBurns14** [JettBurns14/Contest-judging-tool#27]
## **Describe your idea**
Instead of changing "tabs" on /admin, make each one its own view.

## **How would your idea improve the project or user experience?**
- Prevents having to load a lot of data at once with /api/admin/stats, and could cut up that endpoint into a few new ones.
- Would split up bigger admin files like public/js/admin.js into separate smaller ones.
- Would generally be a better way of doing things, allowing each part of /admin to scale independently.

**Comment by lewisevan** [comment]
This was implemented in Pull Request #39
