### ISSUE TITLE
Remove "date" field from new message form

### ISSUE THREAD

**Issue by JettBurns14** [JettBurns14/Contest-judging-tool#28]
## **Describe the feature you'd like**
Is the "date" field on the new announcement form necessary? If the field stands for a message creation date, couldn't that field just be filled automatically during the database INSERT?

## **Is your feature request related to a problem? Please describe.**
Having this field slows me down during development, when I have to input a valid date, when it may not be a necessary feature.

## **Additional context**

![New announcement](https://user-images.githubusercontent.com/24257648/69302930-cbeb5980-0be0-11ea-9310-1a183a4f4101.png)

**Comment by lewisevan** [comment]
Fixed in #40.
