### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by JettBurns14** [JettBurns14/Contest-judging-tool#31]
## **Describe the feature you'd like**
Right now a JSON "Not found" message object is sent back for nonexistent pages. A creative and fun 404 page would be nice to have.

## **Is your feature request related to a problem? Please describe.**
A cryptic JSON message is sent back, instead of a page.

## **Additional context**
![404](https://user-images.githubusercontent.com/24257648/69472297-d850ed00-0d6d-11ea-9a97-5007ba0bdd56.png)

**Comment by lewisevan** [comment]
Add in #40
