### ISSUE TITLE
Public demo version

### ISSUE THREAD

**Issue by JettBurns14** [JettBurns14/Contest-judging-tool#9]
Have all our tool's pages public, which don't send the server any requests unless users have a special web token. This way the entire tool is public, without danger of user interference.

**Comment by Foxbyte14** [comment]
When are you going to make it public? Or make it so we can somehow view it?!

**Comment by JettBurns14** [comment]
Very soon! That’s on my todo list and it should be public in a few weeks.

**Comment by Foxbyte14** [comment]
Awesome! can't wait Jett!

**Comment by JettBurns14** [comment]
_8 months later..._

The work was done a while back, but I just recently pushed the commits (6de79bd thru fa9f569) that wrapped up these changes. The tool will be public in the next few days!
